name: gaussian_splatting
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cuda-toolkit=12.1
  - plyfile=0.8.1
  - python=3.11
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - tqdm
  - jaxtyping
  - typeguard=3.0.2
  - jax
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - pillow